const motivationalQuotes = [
    "The only way to do great work is to love what you do.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "Believe you can and you're halfway there.",
    "Don’t watch the clock; do what it does. Keep going.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "You miss 100% of the shots you don’t take.",
    "The harder you work for something, the greater you’ll feel when you achieve it.",
    "Dream big and dare to fail.",
    "Success is not in what you have, but who you are.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "It always seems impossible until it’s done.",
    "The only place where success comes before work is in the dictionary.",
    "Do not wait to strike till the iron is hot; but make it hot by striking.",
    "The way to get started is to quit talking and begin doing.",
    "Don’t be afraid to give up the good to go for the great.",
    "I find that the harder I work, the more luck I seem to have.",
    "Your time is limited, don’t waste it living someone else’s life.",
    "You only live once, but if you do it right, once is enough.",
    "Life is what happens when you’re busy making other plans.",
    "Don’t let yesterday take up too much of today.",
    "People who are crazy enough to think they can change the world, are the ones who do.",
    "Failure will never overtake me if my determination to succeed is strong enough.",
    "Act as if what you do makes a difference. It does.",
    "The man who has confidence in himself gains the confidence of others.",
    "What you get by achieving your goals is not as important as what you become by achieving your goals.",
    "With the new day comes new strength and new thoughts.",
    "If you want to achieve greatness stop asking for permission.",
    "Things work out best for those who make the best of how things work out.",
    "To live a creative life, we must lose our fear of being wrong.",
    "If you are not willing to risk the usual, you will have to settle for the ordinary.",
    "Trust because you are willing to accept the risk, not because it’s safe or certain.",
    "Good things come to people who wait, but better things come to those who go out and get them.",
    "If you do what you always did, you will get what you always got.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "Just when the caterpillar thought the world was over, it became a butterfly.",
    "Successful entrepreneurs are givers and not takers of positive energy.",
    "Whenever you see a successful person you only see the public glories, never the private sacrifices to reach them.",
    "Opportunities don’t happen, you create them.",
    "Try not to become a person of success, but rather try to become a person of value.",
    "Great minds discuss ideas; average minds discuss events; small minds discuss people.",
    "I have not failed. I’ve just found 10,000 ways that won’t work.",
    "If you don’t value your time, neither will others. Stop giving away your time and talents–start charging for it.",
    "A successful man is one who can lay a firm foundation with the bricks others have thrown at him.",
    "No one can make you feel inferior without your consent.",
    "The whole secret of a successful life is to find out what is one’s destiny to do, and then do it.",
    "If you’re going through hell, keep going.",
    "What seems to us as bitter trials are often blessings in disguise.",
    "The distance between insanity and genius is measured only by success.",
    "Don’t be afraid to give up the good to go for the great.",
    "To be successful you must accept all challenges that come your way. You can’t just accept the ones you like.",
    "Successful people do what unsuccessful people are not willing to do. Don’t wish it were easier, wish you were better.",
    "It is our attitude at the beginning of a difficult task which, more than anything else, will affect its successful outcome.",
    "Don’t let the fear of losing be greater than the excitement of winning.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Logic will get you from A to B. Imagination will take you everywhere.",
    "Let us always meet each other with smile, for the smile is the beginning of love.",
    "The road to success and the road to failure are almost exactly the same.",
    "It is better to fail in originality than to succeed in imitation.",
    "Success usually comes to those who are too busy to be looking for it.",
    "Develop success from failures. Discouragement and failure are two of the surest stepping stones to success.",
    "Nothing in the world can take the place of Persistence. Talent will not; nothing is more common than unsuccessful men with talent. Genius will not; unrewarded genius is almost a proverb. Education will not; the world is full of educated derelicts. The slogan ‘Press On’ has solved and always will solve the problems of the human race.",
    "There are no secrets to success. It is the result of preparation, hard work, and learning from failure.",
    "The best revenge is massive success.",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
    "Success seems to be connected with action. Successful people keep moving. They make mistakes, but they don’t quit.",
    "In order to succeed, your desire for success should be greater than your fear of failure.",
    "You know you are on the road to success if you would do your job and not be paid for it.",
    "I find that the harder I work, the more luck I seem to have.",
    "The starting point of all achievement is desire.",
    "Success is the sum of small efforts, repeated day-in and day-out.",
    "I attribute my success to this: I never gave or took any excuse.",
    "Success isn’t just about what you accomplish in your life; it’s about what you inspire others to do.",
    "Fall seven times and stand up eight.",
    "Some people dream of success while others wake up and work.",
    "If you can dream it, you can do it.",
    "The only way to do great work is to love what you do.",
    "You don’t have to be great to start, but you have to start to be great.",
    "Success is not in what you have, but who you are.",
    "Your limitation—it’s only your imagination.",
    "Push yourself, because no one else is going to do it for you.",
    "Sometimes later becomes never. Do it now.",
    "Great things never come from comfort zones.",
    "Dream it. Wish it. Do it.",
    "Success doesn’t just find you. You have to go out and get it.",
    "The harder you work for something, the greater you’ll feel when you achieve it.",
    "Dream bigger. Do bigger.",
    "Don’t stop when you’re tired. Stop when you’re done.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Do something today that your future self will thank you for.",
    "Little things make big days.",
    "It’s going to be hard, but hard does not mean impossible."
];
console.log(motivationalQuotes[1])